import {
  Network,
  Package,
  Globe,
  Activity,
  Play,
  Key,
  Send,
  Search,
  FlaskConical,
  BookOpen,
  Server,
  Eye,
  CircleDot,
  Blocks,
  Image,
  Hammer,
  Tractor,
  BarChart3,
  Gauge,
  AtSign,
  FileCode,
  Upload,
  Bookmark,
  Bot,
  Music,
  Database,
  FolderPlus,
  FileSearch,
  CreditCard,
  Wheat,
  CheckSquare,
  // Mini-tool icons
  Braces,
  Binary,
  Link,
  Hash,
  Link2,
  Code2,
  GitCompare,
  QrCode,
  FileText,
  Type,
  Quote,
  Fingerprint,
  Tag,
  AlignLeft,
  Clock,
  FileJson,
  Table,
  Timer,
  Regex,
  Lock,
  KeyRound,
  Shield,
  Smartphone,
  Calculator,
  HardDrive,
  ArrowUpDown,
  ArrowRightLeft,
  MapPin,
  Radio,
  TrendingUp,
  Share2,
  Twitter,
  Map,
  Languages,
  Beer,
  Paintbrush,
  Github,
  StickyNote,
  type LucideIcon,
} from "lucide-react";

export interface ToolDefinition {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  actionKey: string;
  category:
    | "code"
    | "testing"
    | "ai-providers"
    | "project"
    | "local-system"
    | "production"
    | "design"
    | "web-tools"
    | "productivity"
    | "utilities";
  disabled?: boolean;
  /** Hide from dropdown (tool has dedicated icon in toolbar) but keep in command palette */
  hiddenInDropdown?: boolean;
  /** For sub-tools: parent tool action key (e.g., "openDevToolkit") */
  parentActionKey?: string;
  /** For sub-tools: the specific sub-tool ID to activate */
  subToolId?: string;
  /** Display group for command palette (e.g., "Developer Tools", "Domain Tools") */
  group?: string;
}

export const TOOL_DEFINITIONS: ToolDefinition[] = [
  // === HIDDEN TOOLS (have dedicated icons in toolbars) ===
  // These still appear in command palette but are hidden from dropdown
  {
    id: "meditation",
    name: "Music / Meditation",
    description: "Ambient music & meditation",
    icon: Music,
    actionKey: "openMeditation",
    category: "productivity",
    hiddenInDropdown: true,
  },
  {
    id: "database-viewer",
    name: "Database Viewer",
    description: "Query SQLite, Postgres, MySQL",
    icon: Database,
    actionKey: "openDatabaseViewer",
    category: "code",
    hiddenInDropdown: true,
  },
  {
    id: "new-project",
    name: "New Project",
    description: "Create from templates",
    icon: FolderPlus,
    actionKey: "openProjectTemplates",
    category: "project",
    hiddenInDropdown: true,
  },
  {
    id: "file-finder",
    name: "File Finder",
    description: "Browse project files",
    icon: FileSearch,
    actionKey: "openFileFinder",
    category: "project",
    hiddenInDropdown: true,
  },
  {
    id: "project-search",
    name: "Project Search",
    description: "Search & replace in files",
    icon: Search,
    actionKey: "openProjectSearch",
    category: "project",
    hiddenInDropdown: true,
  },
  {
    id: "beads-tracker",
    name: "Beads Tracker",
    description: "Manage project issues",
    icon: CircleDot,
    actionKey: "openBeadsTracker",
    category: "project",
    hiddenInDropdown: true,
  },
  {
    id: "auto-build",
    name: "Auto Build",
    description: "Auto-work through issues",
    icon: Bot,
    actionKey: "openAutoBuild",
    category: "project",
    hiddenInDropdown: true,
  },
  {
    id: "farmwork",
    name: "Farmwork",
    description: "Audit & dev workflow",
    icon: Wheat,
    actionKey: "openFarmwork",
    category: "project",
    hiddenInDropdown: true,
  },
  {
    id: "kanban-board",
    name: "Workspace Board",
    description: "Kanban board for workspace tasks",
    icon: CheckSquare,
    actionKey: "openKanbanBoard",
    category: "project",
    hiddenInDropdown: true,
  },

  // === CODE ===
  {
    id: "live-preview",
    name: "Live Preview",
    description: "Preview in browser",
    icon: Play,
    actionKey: "openLivePreview",
    category: "code",
    hiddenInDropdown: true,
  },
  {
    id: "github-manager",
    name: "GitHub Manager",
    description: "Browse repos and connect to GitHub",
    icon: Github,
    actionKey: "openGitHubManager",
    category: "utilities",
    hiddenInDropdown: true,
  },
  {
    id: "storybook-viewer",
    name: "Storybook Viewer",
    description: "Browse Storybook components",
    icon: BookOpen,
    actionKey: "openStorybookViewer",
    category: "testing",
  },
  {
    id: "claude-code-stats",
    name: "Claude Code Stats",
    description: "CLI usage analytics",
    icon: BarChart3,
    actionKey: "openClaudeCodeStats",
    category: "ai-providers",
  },
  {
    id: "limits-monitor",
    name: "Claude Limits Monitor",
    description: "Track API usage limits",
    icon: Gauge,
    actionKey: "openLimitsMonitor",
    category: "ai-providers",
  },

  // === TESTING ===
  {
    id: "test-runner",
    name: "Test Runner",
    description: "Run and view test results",
    icon: FlaskConical,
    actionKey: "openTestRunner",
    category: "testing",
  },
  {
    id: "api-tester",
    name: "API Tester",
    description: "Test HTTP APIs",
    icon: Send,
    actionKey: "openApiTester",
    category: "testing",
  },

  // === PROJECT ===
  {
    id: "farmwork-tycoon",
    name: "Farmwork Tycoon",
    description: "CLI activity as farm game",
    icon: Tractor,
    actionKey: "openFarmworkTycoon",
    category: "project",
    hiddenInDropdown: true,
  },

  // === LOCAL SYSTEM ===
  {
    id: "port-manager",
    name: "Port Manager",
    description: "Manage localhost ports",
    icon: Network,
    actionKey: "openPortManager",
    category: "local-system",
  },
  {
    id: "localhost-tunnel",
    name: "Localhost Tunnel",
    description: "Share localhost publicly",
    icon: Globe,
    actionKey: "openLocalhostTunnel",
    category: "local-system",
  },
  {
    id: "background-services",
    name: "Background Services",
    description: "Manage dev services",
    icon: Server,
    actionKey: "openBackgroundServices",
    category: "local-system",
  },
  {
    id: "system-health",
    name: "System Health",
    description: "Dev tools & resources",
    icon: Activity,
    actionKey: "openSystemHealth",
    category: "local-system",
  },
  {
    id: "homebrew-manager",
    name: "Homebrew Manager",
    description: "Manage Homebrew packages",
    icon: Beer,
    actionKey: "openHomebrewManager",
    category: "local-system",
  },
  {
    id: "system-cleaner",
    name: "System Cleaner",
    description: "Clean up disk space",
    icon: HardDrive,
    actionKey: "openSystemCleaner",
    category: "local-system",
  },

  // === PRODUCTION ===
  {
    id: "overwatch",
    name: "Overwatch",
    description: "Monitor prod services",
    icon: Eye,
    actionKey: "openOverwatch",
    category: "production",
    hiddenInDropdown: true,
  },
  {
    id: "netlify-ftp",
    name: "Netlify FTP",
    description: "Deploy with retro FTP",
    icon: Upload,
    actionKey: "openNetlifyFtp",
    category: "production",
    hiddenInDropdown: true,
  },
  {
    id: "web-backup",
    name: "Web Backup",
    description: "Encrypted cloud backup settings",
    icon: Lock,
    actionKey: "openWebBackup",
    category: "production",
  },

  // === DESIGN ===
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate favicons",
    icon: Image,
    actionKey: "openFaviconGenerator",
    category: "design",
  },
  {
    id: "designer-tool",
    name: "Designer Tool",
    description: "AI-powered image generation",
    icon: Paintbrush,
    actionKey: "openDesignerTool",
    category: "design",
  },

  // === TOOLKITS ===
  {
    id: "dev-toolkit",
    name: "Developer Tools",
    description: "Text & encoding utilities",
    icon: Hammer,
    actionKey: "openDevToolkit",
    category: "web-tools",
  },
  {
    id: "domain-tools",
    name: "Domain Tools",
    description: "WHOIS, DNS & SSL checks",
    icon: AtSign,
    actionKey: "openDomainTools",
    category: "web-tools",
  },
  {
    id: "seo-tools",
    name: "SEO Tools",
    description: "Meta tags & Open Graph",
    icon: FileCode,
    actionKey: "openSeoTools",
    category: "web-tools",
  },

  // === PRODUCTIVITY ===
  {
    id: "bookmarks",
    name: "Bookmarks",
    description: "Manage your bookmarks",
    icon: Bookmark,
    actionKey: "openBookmarks",
    category: "productivity",
    hiddenInDropdown: true,
  },
  {
    id: "subscription-manager",
    name: "Subscription Manager",
    description: "Track subscriptions",
    icon: CreditCard,
    actionKey: "openSubscriptions",
    category: "productivity",
    hiddenInDropdown: true,
  },

  // === UTILITIES ===
  {
    id: "mcp-manager",
    name: "MCP Servers",
    description: "Manage MCP servers",
    icon: Blocks,
    actionKey: "openMcpManager",
    category: "utilities",
  },
  {
    id: "env-manager",
    name: "Environment Variables",
    description: "Manage .env & secrets",
    icon: Key,
    actionKey: "openEnvManager",
    category: "utilities",
  },
  {
    id: "node-modules-cleaner",
    name: "Node Modules Cleaner",
    description: "Clean node_modules",
    icon: Package,
    actionKey: "openNodeModulesCleaner",
    category: "utilities",
  },
  {
    id: "just-command-manager",
    name: "Just Command Manager",
    description: "Manage justfile recipes",
    icon: Play,
    actionKey: "openJustCommandManager",
    category: "utilities",
  },
  {
    id: "universal-viewer",
    name: "File Viewer",
    description: "Open any file type",
    icon: Eye,
    actionKey: "openUniversalViewer",
    category: "utilities",
    hiddenInDropdown: true,
  },
  {
    id: "scratchpad",
    name: "Scratchpad",
    description: "Quick text notepad",
    icon: StickyNote,
    actionKey: "openScratchpad",
    category: "utilities",
  },

  // === DEV TOOLKIT MINI-TOOLS ===
  { id: "dt-json-formatter", name: "JSON Formatter", description: "Format & validate JSON", icon: Braces, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "json-formatter", group: "Developer Tools" },
  { id: "dt-base64", name: "Base64 Encoder", description: "Encode/decode Base64", icon: Binary, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "base64", group: "Developer Tools" },
  { id: "dt-url-encode", name: "URL Encoder", description: "Encode/decode URLs", icon: Link, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "url-encode", group: "Developer Tools" },
  { id: "dt-html-entity", name: "HTML Entity", description: "Encode/decode HTML", icon: Code2, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "html-entity", group: "Developer Tools" },
  { id: "dt-string-escape", name: "String Escape", description: "Escape strings", icon: Quote, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "string-escape", group: "Developer Tools" },
  { id: "dt-text-diff", name: "Text Diff", description: "Compare two texts", icon: GitCompare, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "text-diff", group: "Developer Tools" },
  { id: "dt-case-converter", name: "Case Converter", description: "Convert text case", icon: Type, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "case-converter", group: "Developer Tools" },
  { id: "dt-lorem-ipsum", name: "Lorem Ipsum", description: "Generate placeholder", icon: FileText, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "lorem-ipsum", group: "Developer Tools" },
  { id: "dt-slug-generator", name: "Slug Generator", description: "Create URL slugs", icon: Tag, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "slug-generator", group: "Developer Tools" },
  { id: "dt-word-counter", name: "Word Counter", description: "Count words & chars", icon: AlignLeft, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "word-counter", group: "Developer Tools" },
  { id: "dt-list-sorter", name: "List Sorter", description: "Sort & dedupe lists", icon: ArrowUpDown, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "list-sorter", group: "Developer Tools" },
  { id: "dt-json-yaml", name: "JSON/YAML Converter", description: "Convert JSON ↔ YAML", icon: FileJson, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "json-yaml", group: "Developer Tools" },
  { id: "dt-csv-json", name: "CSV/JSON Converter", description: "Convert CSV ↔ JSON", icon: Table, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "csv-json", group: "Developer Tools" },
  { id: "dt-timestamp", name: "Timestamp Converter", description: "Unix ↔ date", icon: Clock, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "timestamp", group: "Developer Tools" },
  { id: "dt-cron-parser", name: "Cron Parser", description: "Explain cron syntax", icon: Timer, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "cron-parser", group: "Developer Tools" },
  { id: "dt-regex-tester", name: "Regex Tester", description: "Test regular expressions", icon: Regex, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "regex-tester", group: "Developer Tools" },
  { id: "dt-uuid-generator", name: "UUID Generator", description: "Generate UUIDs", icon: Fingerprint, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "uuid-generator", group: "Developer Tools" },
  { id: "dt-password-generator", name: "Password Generator", description: "Secure passwords", icon: Lock, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "password-generator", group: "Developer Tools" },
  { id: "dt-qr-generator", name: "QR Code Generator", description: "Generate QR codes", icon: QrCode, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "qr-generator", group: "Developer Tools" },
  { id: "dt-placeholder-image", name: "Placeholder Image", description: "Generate placeholders", icon: Image, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "placeholder-image", group: "Developer Tools" },
  { id: "dt-hash-generator", name: "Hash Generator", description: "MD5, SHA hashes", icon: Hash, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "hash-generator", group: "Developer Tools" },
  { id: "dt-jwt-debugger", name: "JWT Debugger", description: "Decode JWT tokens", icon: Key, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "jwt-debugger", group: "Developer Tools" },
  { id: "dt-bcrypt-generator", name: "Bcrypt Generator", description: "Hash passwords", icon: KeyRound, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "bcrypt-generator", group: "Developer Tools" },
  { id: "dt-hmac-generator", name: "HMAC Generator", description: "HMAC signatures", icon: Shield, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "hmac-generator", group: "Developer Tools" },
  { id: "dt-url-parser", name: "URL Parser", description: "Parse URL parts", icon: Link2, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "url-parser", group: "Developer Tools" },
  { id: "dt-http-status", name: "HTTP Status Codes", description: "Status reference", icon: Globe, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "http-status", group: "Developer Tools" },
  { id: "dt-user-agent", name: "User Agent Parser", description: "Parse user agents", icon: Smartphone, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "user-agent", group: "Developer Tools" },
  { id: "dt-ip-address", name: "IP Address Tool", description: "Analyze IPs", icon: Network, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "ip-address", group: "Developer Tools" },
  { id: "dt-number-base", name: "Number Base Converter", description: "Hex, binary, decimal", icon: Calculator, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "number-base", group: "Developer Tools" },
  { id: "dt-byte-size", name: "Byte Size Converter", description: "KB, MB, GB, TB", icon: HardDrive, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "byte-size", group: "Developer Tools" },
  { id: "dt-html-css-validator", name: "HTML/CSS Validator", description: "Validate code", icon: FileCode, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "html-css-validator", group: "Developer Tools" },
  { id: "dt-exif-remover", name: "EXIF Remover", description: "Remove image metadata", icon: Image, actionKey: "openDevToolkit", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDevToolkit", subToolId: "exif-remover", group: "Developer Tools" },

  // === DOMAIN TOOLS MINI-TOOLS ===
  { id: "dom-whois", name: "WHOIS Lookup", description: "Domain registration", icon: FileSearch, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "whois", group: "Domain Tools" },
  { id: "dom-availability", name: "Domain Availability", description: "Check if registered", icon: Globe, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "availability", group: "Domain Tools" },
  { id: "dom-dns", name: "DNS Lookup", description: "Query DNS records", icon: Server, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "dns", group: "Domain Tools" },
  { id: "dom-propagation", name: "DNS Propagation", description: "Global DNS check", icon: Radio, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "propagation", group: "Domain Tools" },
  { id: "dom-ssl", name: "SSL Certificate", description: "Check SSL details", icon: Shield, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "ssl", group: "Domain Tools" },
  { id: "dom-headers", name: "HTTP Headers", description: "Inspect headers", icon: FileSearch, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "headers", group: "Domain Tools" },
  { id: "dom-ip", name: "IP Address Lookup", description: "Geolocation & ISP", icon: MapPin, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "ip", group: "Domain Tools" },
  { id: "dom-redirect", name: "Redirect Tracker", description: "Follow redirects", icon: ArrowRightLeft, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "redirect", group: "Domain Tools" },
  { id: "dom-dead-links", name: "Dead Link Checker", description: "Find broken links", icon: Link2, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "dead-links", group: "Domain Tools" },
  { id: "dom-lighthouse", name: "Lighthouse Auditor", description: "Run audits", icon: TrendingUp, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "lighthouse", group: "Domain Tools" },
  { id: "dom-favicon", name: "Favicon Grabber", description: "Extract favicons", icon: Image, actionKey: "openDomainTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openDomainTools", subToolId: "favicon-grabber", group: "Domain Tools" },

  // === SEO TOOLS MINI-TOOLS ===
  { id: "seo-meta-tags", name: "Meta Tags Generator", description: "Generate meta tags", icon: FileCode, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "meta-tags", group: "SEO Tools" },
  { id: "seo-open-graph", name: "Open Graph Generator", description: "Facebook/LinkedIn", icon: Share2, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "open-graph", group: "SEO Tools" },
  { id: "seo-twitter-card", name: "Twitter Card Generator", description: "Twitter cards", icon: Twitter, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "twitter-card", group: "SEO Tools" },
  { id: "seo-structured-data", name: "JSON-LD Generator", description: "Schema.org data", icon: Code2, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "structured-data", group: "SEO Tools" },
  { id: "seo-canonical", name: "Canonical URL Helper", description: "Canonical links", icon: Link, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "canonical", group: "SEO Tools" },
  { id: "seo-robots-txt", name: "Robots.txt Generator", description: "Generate robots.txt", icon: Bot, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "robots-txt", group: "SEO Tools" },
  { id: "seo-llms-txt", name: "LLMs.txt Generator", description: "AI-friendly summary", icon: FileText, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "llms-txt", group: "SEO Tools" },
  { id: "seo-sitemap", name: "Sitemap Generator", description: "XML sitemap", icon: Map, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "sitemap", group: "SEO Tools" },
  { id: "seo-hreflang", name: "Hreflang Generator", description: "Multi-language tags", icon: Languages, actionKey: "openSeoTools", category: "web-tools", hiddenInDropdown: true, parentActionKey: "openSeoTools", subToolId: "hreflang", group: "SEO Tools" },
];
